name: Build documentation

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.usabud }}
        password: ${{ secrets.1_Love_Docker! }}
        registry: docker.io
        repository: 3r1co/cd
        tag_with_sha: true
