name: Build documentation

on:
  push:
    branches:
    - master
jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PW }}
        registry: docker.io
        repository: usabud/ssc
        tag_with_sha: true
  
    - name: Run SonarCloud
      uses: sonarcloud/analyse
        with:
          projectKey: usabud_ssc
          orgnization: usabud
          hostUrl: <predefined sonarcloud host url>
