name: Build documentation

on:
  push:
    branches:
    - master
jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Run SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
    - name: Archive dependency check reports  
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports
    
    - uses: actions/checkout@v2
    - name: Install NPM dependencies
      run: |
        npm install --production --unsafe-perm
    
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PW }}
        registry: docker.io
        repository: usabud/ssc
        tag_with_sha: true
